kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: smokeping-data
  namespace: smokeping
  labels:
    k8s-app: smokeping
spec:
  storageClassName: local-data-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
