apiVersion: v1
kind: PersistentVolume
metadata:
  name: smokeping-pv-data
spec:
  capacity:
    storage: 15Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-data-storage
  local:
    path: /media/usb-cruzer/smokeping-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node-1-k3s
